### ISSUE TITLE
Weird event nesting 

### ISSUE THREAD

**Issue by M0nica** [react-ladies/React-Ladies#35]
<img width="1302" alt="Screen Shot 2019-08-03 at 10 13 26 PM" src="https://user-images.githubusercontent.com/6998954/62418698-b35d3080-b63d-11e9-9b26-d7aa07f92565.png">
There is some strange nesting happening for one of of the Meetup events

It only happens in production (when deployed to Netlify) but not locally. 

I've opened an issue with the Gatsby theme maker https://github.com/matthieuauger/gatsby-theme-meetup/issues/6

**Comment by matthieuauger** [comment]
Hey there! Thanks for reaching out :)

It seems be caused by the slice on the meetup description here https://github.com/M0nica/React-Ladies/blob/master/src/%40matthieuauger/gatsby-theme-meetup/components/Meetup/Meetup.component.js#L54

Which cuts the link of the meetup and results in weird HTML markup 
![image](https://user-images.githubusercontent.com/1172099/62430823-bcbfc900-b721-11e9-94b7-1c1af1424a33.png)

If you want a really quick way to remove the display bug, you could change the slice number. 

Now we could figure a way to fix it right directly in the theme. The use-case of limiting the description is necessary and I tried some CSS options to hide the overflow but sometimes the cut is not in the right place.

![image](https://user-images.githubusercontent.com/1172099/62431052-483a5980-b724-11e9-9c41-1735abdc646e.png)
  
I'll try it again tomorrow, if you have some ideas on the topic I can try them as well 💡

**Comment by M0nica** [comment]
Oo interesting. Thanks for looking into this for me. Yeah, I found displaying the full descriptions to be a bit overwhelming for the site

This Shave package for truncating text looks interesting but I’m not sure if it handles markup well. https://github.com/dollarshaveclub/shave although, I think the most complicated markup I’ll have in a Meetup event description is a url. I’ll try to think of some more flexible solutions.

**Comment by M0nica** [comment]
This is related to the old site and therefore is no longer relevant.
